/** Tereyağlı Pirinç Pilavı — zamanlayıcı ağırlıklı, kritik güvenlik adımı yok. */
import type { Recipe } from '../engine/types';

export const pilav: Recipe = {
  id: 'pilav',
  title: { tr: 'Tereyağlı Pirinç Pilavı', en: 'Buttery Rice Pilaf' },
  servings: 4,
  locale: 'tr',
  summary: {
    tr: 'Tane tane, şehriyeli klasik pilav.',
    en: 'Fluffy, separate grains — the classic vermicelli pilaf.',
  },
  totalMinutes: 30,
  nodes: [
    {
      id: 'rinse',
      title: 'Pirinci yıka',
      instruction: 'Pirinci berrak su gelene dek yıka, ılık suda beklet.',
      kind: 'prep',
      requires: [],
      completion: 'user',
      voice_on_enter: 'Pirinci yıkayıp biraz bekletelim.',
    },
    {
      id: 'toast',
      title: 'Şehriyeyi kavur',
      instruction: 'Tereyağında şehriyeyi pembeleştir, süzülmüş pirinci ekle kavur.',
      kind: 'action',
      requires: ['rinse'],
      completion: 'timer',
      durationSec: 180,
      voice_on_enter: 'Şehriyeyi pembeleşene dek kavuralım.',
      recovery_rules: { yaktim: 'Şehriye karardıysa baştan başla; düşük ateşte kavur.' },
    },
    {
      id: 'add_water',
      title: 'Su ekle',
      instruction: 'Sıcak su ve tuzu ekle, karıştır.',
      kind: 'action',
      requires: ['toast'],
      completion: 'user',
      voice_on_enter: 'Sıcak suyu ekle, bir karıştır.',
    },
    {
      id: 'cook',
      title: 'Pişir',
      instruction: 'Kapağı kapat, suyunu çekene dek kısık ateşte pişir.',
      kind: 'action',
      requires: ['add_water'],
      completion: 'timer',
      durationSec: 900,
      voice_on_enter: 'Kısık ateşte suyunu çekmesini bekleyelim.',
      voice_on_complete: 'Su çekildi.',
      recovery_rules: { sulu: 'Su kaldıysa kapağı açıp birkaç dakika daha pişir.' },
    },
    {
      id: 'rest',
      title: 'Demlendir',
      instruction: 'Ocaktan al, üzerine bez örtüp demlendir.',
      kind: 'finish',
      requires: ['cook'],
      completion: 'timer',
      durationSec: 600,
      voice_on_enter: 'Bezle örtüp demlenmeye bırak, tanesi tane olur.',
      voice_on_complete: 'Pilav hazır, afiyet olsun!',
    },
  ],
};
