/** Tavuk Sote — kritik tavuk pişirme adımı (iç sıcaklık 74°C). */
import type { Recipe } from '../engine/types';

export const tavukSote: Recipe = {
  id: 'tavuk-sote',
  title: { tr: 'Tavuk Sote', en: 'Chicken Sauté' },
  servings: 3,
  locale: 'tr',
  summary: {
    tr: 'Sebzeli, sulu, pratik tavuk sote.',
    en: 'A quick, saucy chicken sauté with vegetables.',
  },
  totalMinutes: 30,
  nodes: [
    {
      id: 'chop_chicken',
      title: 'Tavuğu doğra',
      instruction: 'Tavuk göğsünü kuşbaşı doğra.',
      kind: 'prep',
      requires: [],
      parallel_with: ['chop_veg'],
      completion: 'user',
      voice_on_enter: 'Tavuğu kuşbaşı doğrayalım.',
    },
    {
      id: 'chop_veg',
      title: 'Sebzeleri doğra',
      instruction: 'Biber, soğan ve domatesi doğra.',
      kind: 'prep',
      requires: [],
      parallel_with: ['chop_chicken'],
      completion: 'user',
    },
    {
      id: 'sear',
      title: 'Tavuğu soteleyin',
      instruction: 'Yağı ısıt, tavuğu suyunu çekip renk alana dek soteleme.',
      kind: 'action',
      requires: ['chop_chicken'],
      completion: 'timer',
      durationSec: 480,
      voice_on_enter: 'Tavuğu kızgın yağda soteleyelim.',
      voice_on_complete: 'Tavuk renk aldı.',
      recovery_rules: { yaktim: 'Ateşi kıs, dipte yanma varsa biraz su ekleyip kazı.' },
    },
    {
      id: 'add_veg',
      title: 'Sebzeleri ekle',
      instruction: 'Sebzeleri ekle, yumuşayana dek kavur.',
      kind: 'action',
      requires: ['sear', 'chop_veg'],
      completion: 'timer',
      durationSec: 420,
      voice_on_enter: 'Sebzeleri ekle, birlikte kavuralım.',
    },
    {
      id: 'finish_cook',
      title: 'Pişir',
      instruction: 'Baharatla; tavuk tamamen pişene dek pişir.',
      kind: 'action',
      requires: ['add_veg'],
      completion: 'user',
      safety: {
        critical: true,
        message:
          'Tavuk tamamen pişmeli — en kalın parçada pembe kalmamalı, iç sıcaklık 74°C olmalı. Emin değilsen biraz daha pişir.',
        minInternalTempC: 74,
      },
      voice_on_enter: 'Tavuğun içinin de piştiğinden emin olalım.',
      voice_on_complete: 'Parçaları kesip pembe kalmadığını kontrol et.',
    },
    {
      id: 'serve',
      title: 'Servis et',
      instruction: 'Sıcak servis et.',
      kind: 'finish',
      requires: ['finish_cook'],
      completion: 'user',
      voice_on_enter: 'Afiyet olsun!',
    },
  ],
};
